name: "CPAN unit tests"
description: "Run standard CPAN-style unit tests for a distribution"

inputs:
  perl_version:
    description: "Perl version to use (e.g. 5.42)"
    required: true

  os:
    description: "Runner label (e.g. ubuntu-latest, windows-latest, macos-latest)"
    required: true

  testing_context:
    description: "JSON array of testing context flags, e.g. ['author','release']"
    required: false
    default: '[ ]'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ inputs.perl_version }}

    - name: Perl version
      run: perl -V
      shell: bash

    - name: Install modules
      run: |
        cpanm --notest --with-configure --with-develop --no-man-pages --installdeps .
      shell: bash

    - name: Configure with Makefile.PL
      id: configure-with-eumm
      if: ${{ hashFiles('Makefile.PL') != '' }}
      run: |
        perl Makefile.PL
        make
      shell: bash

    - name: Configure with Build.PL
      id: configure-with-mb
      if: ${{ hashFiles('Build.PL') != '' }}
      run: |
        perl Build.PL
        ./Build
      shell: bash

    - name: Set testing context
      if: ${{ !startsWith(inputs.os, 'windows') }}
      run: |
        printf '%s\n' '${{ inputs.testing_context }}' | \
        jq -r '.[]' | \
        tr '[:lower:]' '[:upper:]' | \
        while read -r item; do
          printf '%s_TESTING=1\n' "${item}" >> "${GITHUB_ENV}"
        done
      shell: bash

    - name: Run tests with make
      if: steps.configure-with-eumm.outcome == 'success'
      run: |
        make TEST_VERBOSE=1 test
      shell: bash

    - name: Run tests with ./Build
      if: steps.configure-with-mb.outcome == 'success'
      run: |
        ./Build verbose=1 test
      shell: bash

    - name: Archive CPAN logs on Windows
      if: ${{ failure() && inputs.os == 'windows-latest' }}
      uses: actions/upload-artifact@v5
      with:
        name: cpan_log
        path: C:\Users\RUNNER~1\.cpanm\work\*\build.log
        retention-days: 5

    - name: Archive CPAN logs on Unix
      if: ${{ failure() && inputs.os != 'windows-latest' }}
      uses: actions/upload-artifact@v5
      with:
        name: cpan_log
        path: /home/runner/.cpanm/work/*/build.log
        retention-days: 5

