name: Release to CPAN

on:
  workflow_call:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        perl:
          - 'latest'
    name: Build and release
    steps:
      - uses: actions/checkout@v4
      - name: Perl version
        run: perl -V
      - name: Install cpanm and jq
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y cpanminus jq
      - name: Install modules
        run: sudo cpanm --notest --installdeps --with-suggests --with-recommends --with-develop --with-configure .
      - name: Build with Build.PL
        if: ${{ hashFiles('Build.PL') != '' }}
        run: |
          sudo perl Build.PL
          sudo ./Build dist
          sudo ./Build disttest
      - name: Build with Makefile.PL
        if: ${{ hashFiles('Build.PL') == '' }}
        run: |
          sudo perl Makefile.PL
          sudo make dist
          sudo make disttest
      - name: Do the other stuff
        run: |
          jq -r .name META.json
          jq -r .version META.json
          ls -l *.tar.gz

