name: Kwality

on:
  workflow_call:

jobs:
  kwality:
    runs-on: ubuntu-latest
    container: davorg/perl-perlcritic
    steps:
      - uses: actions/checkout@v4
      - name: Perl version
        run: perl -V
      - name: Run perlcritic
        run: |
          perlcritic .
        continue-on-error: true

