name: Unit tests

on:
  workflow_call:

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'windows-latest'
          - 'macos-latest'
          - 'ubuntu-latest'
        perl:
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - 'latest'
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Install Dist::Zilla
        run: cpanm --notest Dist::Zilla
      - name: Install Dist::Zilla plugins
        run: dzil authordeps | cpanm --notest
      - name: Install modules
        run: dzil listdeps --author | cpanm --notest
      - name: Run tests
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          dzil test
      - name: Archive CPAN logs on Windows
        if: ${{ failure() && matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: cpan_log
          path: C:\Users\RUNNER~1\.cpanm\work\*\build.log
          retention-days: 5
      - name: Archive CPAN logs on Unix
        if: ${{ failure() && matrix.os != 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: cpan_log
          path: /home/runner/.cpanm/work/*/build.log
          retention-days: 5
