name: Cyclomatic complexity

on:
  workflow_call:
    inputs:
      level:
        type: number
        required: false
        default: 5
jobs:
  cyclomatic-complexity:
    runs-on: ubuntu-latest
    steps:
      - name: Install cpanminus
        run: sudo apt-get install -y cpanminus
      - name: Install Perl::Metrics::Simple
        run: sudo cpanm Perl::Metrics::Simple
      - name: Check out code
        uses: actions/checkout@v4
      - name: Perl version
        run: perl -V
      - name: Run countperl
        run: |
          countperl lib

