name: Basic CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: davorg/perl-perlcritic
    steps:
      - uses: actions/checkout@v3
      - name: Perl version
        run: perl -V
      - name: Run perlcritic
        run: |
          perlcritic .
          echo RC: $?
          if [ "$?" -eq 1 ]; then exit 1; else exit 0; fi

